### ISSUE TITLE
getting decument reader should be initialize first error

### ISSUE THREAD

**Issue by shunishya** [regulaforensics/DocumentReader-Android#1]
hello,
Previously my application was working fine with mrz but recently im getting following error:

  java.lang.IllegalStateException: Document Reader is not initialized. Please, call Init() before use!
                                                                          at com.regula.sdk.DocumentReader.a(Unknown Source)
                                                                          at com.regula.sdk.CaptureActivity$3.onPreviewFrame(Unknown Source)
                                                                          at android.hardware.Camera$EventHandler.handleMessage(Camera.java:985)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:146)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                          at dalvik.system.NativeStart.main(Native Method)

Please help.

**Comment by mskvorcovs** [comment]
Hello,

Does the Init() method return true after being called? If not, this might
be because your development license has expired.

Best regards,
Maris Skvorcovs
