### ISSUE TITLE
Credit Card reader dependency

### ISSUE THREAD

**Issue by Echarde1** [regulaforensics/DocumentReader-Android#12]
Android API 24

When trying to scan a **credit card** this exception is being thrown:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vtb.cardsscanner, PID: 4259
    java.lang.NoSuchFieldError: No instance field imgBytes of type [B in class Lcom/regula/core/ImageResult; or its superclasses (declaration of 'com.regula.core.ImageResult' appears in /data/app/(my app package)/split_lib_dependencies_apk.apk)
        at com.regula.documentreader.api.DocumentReader.parseResults(DocumentReader.java:955)
        at com.regula.documentreader.api.RecognitionTask.onPostExecute(RecognitionTask.java:82)
        at com.regula.documentreader.api.RecognitionTask.onPostExecute(RecognitionTask.java:10)
        at android.os.AsyncTask.finish(AsyncTask.java:660)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

Moreover, the library inits only with the second attempt

**Comment by vyakimchik** [comment]
Hello. The issue will be closed because the credit card recognition functionality was completely changed and it's available in the following [Core types](https://docs.regulaforensics.com/android/core) now. Please use it and inform us if you encounter any issues.
