### ISSUE TITLE
Camera crashes after autofocus on Android 4.2.2

### ISSUE THREAD

**Issue by oleg30** [regulaforensics/DocumentReader-Android#8]
Sometimes, when a picture is taken by pressing capture button (scenario - "FullProcess", launched method - DocumentReader.Instance().showScanner(completion)), after autofocus is done (logs shows "CameraFragment: AutoFocus success: true") everything hangs up and no response (also no response on back and home buttons). After some time you can go to home screen by home button but hanged app doesn't response. After manually killing that process, camera app of the device shows error ("can not connect to camera") and doesn't launch. When trying to start camera in app by DocumentReader, logs shows error: "Fail to connect to camera service". Only restarting the device helps.
Android 4.2.2.

**Comment by DmitrySmolyakov** [comment]
Sorry we can't reproduce your issue on our side. We have released new version, where made many updated for devices with Android version <5. Please take a look.

**Comment by oleg30** [comment]
Maybe it somehow connected with this error, which occurs in strict mode some time after image is taken with camera and successfully recognized in FullProcess scenario? 

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at android.view.Surface.<init>(Surface.java:289)
        at android.view.SurfaceView.<init>(SurfaceView.java:96)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at android.view.LayoutInflater.createView(LayoutInflater.java:587)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

        at com.regula.documentreader.api.CaptureActivity2.onCreate(CaptureActivity2.java:189)

        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
        at android.app.ActivityThread.access$600(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5074)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by DmitrySmolyakov** [comment]
We’ve released the new version of the SDK - 5.0. Plenty of changes have been done.

We also relocated our documentation from GitHub Wiki to https://docs.regulaforensics.com/home/.

The changelog can be found in the documentation or in the GitHub repositories https://github.com/regulaforensics.
