### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by oleg30** [regulaforensics/DocumentReader-Android#9]
When working with DocumentReader-Android sample app in Mrz scenario after several (20-25) scans (DocumentReader.Instance().showScanner(completion)) an error occurs:

E/Camera-JNI: Couldn't allocate byte array for JPEG data
E/dalvikvm-heap: Out of memory on a 1382416-byte allocation.

And also sometimes it can fail with:

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:299)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
        at java.util.concurrent.FutureTask.run(FutureTask.java:239)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.OutOfMemoryError
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:689)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:666)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
        at com.regula.core.NativeWrapper.getRichDocumentImages(Native Method)
        at com.regula.core.NativeWrapper.GetRichDocumentImages(NativeWrapper.java:95)
        at com.regula.documentreader.api.DocumentReader.parseResults(DocumentReader.java:936)
        at com.regula.documentreader.api.DocumentReader.access$700(DocumentReader.java:94)
        at com.regula.documentreader.api.DocumentReader$RecognitionTask.doInBackground(DocumentReader.java:1263)
        at com.regula.documentreader.api.DocumentReader$RecognitionTask.doInBackground(DocumentReader.java:1202)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:856) 

(Android 4.2.2, 1Gb RAM, using last version of com.regula.documentreader.full:core and com.regula.documentreader:api).

**Comment by DmitrySmolyakov** [comment]
Fixed in latest release version 4.2
